# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4052e6ddd8cd7406c5fc316da0e09a8acc14f1df4fc99c9b6f9f58a663ce7d4c734b87214519c0d950807ef193f053609b4343f1eaa1189692c085eb8bc3985

test:
  secret_key_base: 3740fdb00063d3223be05888e66f9303d8db1ae6b82ccb1c7d5365f77462e1a9f4c06185b8b950780206fb8ee9adef4f84b5b9e1fbed749e7dd63d153ee7a2fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
